- name: Get all namespaces
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Namespace
  register: ns_list

- include_tasks: _netpol/dns-egress.yml
  vars: { ns: "{{ item }}" }
  loop: "{{ ['container-registry', 'default'] | intersect(ns_list.resources | map(attribute='metadata.name') | list) }}"

- name: Apply egress policy to namespaces (block LAN except gateway + NFS)
  vars:
    excluded_namespaces:
      - kube-system # Mainly for NFS access to the host server
      - kube-public
      - kube-node-lease
      #- container-registry
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: block-local-lan-egress-except-gw-nfs
        namespace: "{{ item.metadata.name }}"
      spec:
        podSelector: {}
        policyTypes: [Egress]
        egress:
          - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
                  except:
                    - "{{ network.private_cidr }}"
                    - "10.1.0.0/16"        # MicroK8s pod CIDR (default)
                    - "10.152.183.0/24"    # MicroK8s service CIDR (default)
          - to:
              - ipBlock:
                  cidr: "{{ network.host_gateway }}/32"
  loop: "{{ ns_list.resources }}"
  when: item.metadata.name not in excluded_namespaces
